[database]
mongodb = "mongodb://database"
redis = "redis://redis/"

[hosts]
app = "https://chat.elysium.chat"
api = "http://api.chat.elysium.chat/"
events = "wss://events.chat.elysium.chat"
autumn = "https:///files.chat.elysium.chat"
january = "https:///metadata.chat.elysium.chat
voso_legacy = ""
voso_legacy_ws = ""

[api]

[api.registration]
invite_only = false

[api.smtp]
host = ""
username = ""
password = ""
from_address = ""

[api.vapid]
private_key = "LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tDQpNSGNDQVFFRUlDZDZ6dGV2b1BrSG9qZ1RS cHZmaDZ5RmJOMm5UYmFvcmhsOVo0U0xGQjFPb0FvR0NDcUdTTTQ5DQpBd0VIb1VRRFFnQUVCbFMx cThsMnZsQTlGR29Lbng2VUwxLzNnb3pVRWF1QkhIbzZoWlJTeHNGT3NYZUlScUZuDQpMSlNETFh1 RzR4K1N4ZGh3NTVEcjlrOGliZ2Z4NGxzcU9BPT0NCi0tLS0tRU5EIEVDIFBSSVZBVEUgS0VZLS0t LS0NCg=="
public_key = "BAZUtavJdr5QPRRqCp8elC9f94KM1BGrgRx6OoWUUsbBTrF3iEahZyyUgy17huMfksXYcOeQ6_ZPIm4H8eJbKjg="

[api.fcm]
api_key = ""

[api.security]
authifier_shield_key = ""
voso_legacy_token = ""
trust_cloudflare = false

[api.security.captcha]
hcaptcha_key = ""
hcaptcha_sitekey = ""

[api.workers]
max_concurrent_connections = 50

[features]
webhooks_enabled = true

[features.limits]

[features.limits.default]
group_size = 100
bots = 5
message_length = 2000
message_embeds = 5
message_replies = 5
message_attachments = 5
message_reactions = 20
servers = 100
server_emoji = 100
server_roles = 200
server_channels = 200

attachment_size = 20000000
avatar_size = 4000000
background_size = 6000000
icon_size = 2500000
banner_size = 6000000
emoji_size = 500000

[sentry]
api = ""
events = ""
